#!/usr/bin/env bash
# This script displays list of curently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display a user_oriented format
# Show process hierachy

ps -a -x -u -f
