#!/usr/bin/env bash
# This script extends previous exercise command a nd displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# You can not use pgrep
# shellcheck disable=sc2009

./1-list_your_processes | grep "bash"
