#!/usr/bin/env bash

# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" on a new line after "Best School".

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count+1))
done
